/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stry4ka_inputClone_nativecpp_NativeListenerCPP */

#ifndef _Included_com_stry4ka_inputClone_nativecpp_NativeListenerCPP
#define _Included_com_stry4ka_inputClone_nativecpp_NativeListenerCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stry4ka_inputClone_nativecpp_NativeListenerCPP
 * Method:    setupListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stry4ka_inputClone_nativecpp_NativeListenerCPP_setupListener
  (JNIEnv *, jobject);

/*
 * Class:     com_stry4ka_inputClone_nativecpp_NativeListenerCPP
 * Method:    blockInput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_stry4ka_inputClone_nativecpp_NativeListenerCPP_blockInput
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
